fasta:
  url: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/GRCh38.primary_assembly.genome.fa.gz
  file: GRCh38.primary_assembly.genome.fa

vcf: example.vcf

splicemap_dir: ../splicing_outlier_prediction/precomputed/splicemap_gtex_v8/

splicing_pred:
  mmsplice_splicemap: mmsplice_splicemap.csv
  spliceai: spliceai.csv
  spliceai_vcf: spliceai.vcf
  absplice_dna: absplice_dna.csv