name: absplice
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python >= 3.8
  - cython
  - tensorflow
  - spliceai
  - snakemake
  - rocksdb
  - python-rocksdb
  - pytest
  - tabix
  - setuptools
  - kipoiseq>=0.7
  - cyvcf2
  - scipy
  - pandas
  - pyfaidx
  - tqdm
  - click
  - pyranges>=0.0.71
  - pip
  - pyarrow
  - pip:
    - mmsplice
    - interpret
    - git+https://github.com/gagneurlab/splicemap.git
    