gene_map: ../absplice/precomputed/GENE_MAP.tsv.gz

cat_count_table: 
  raw: data/resources/absplice_rna_related_files/processed/cat_count_table/tissue_cat={tissue_cat}_count_table_raw.csv
  updated: data/resources/absplice_rna_related_files/processed/cat_count_table/tissue_cat={tissue_cat}_count_table.csv
  # with_annotation: data/resources/absplice_rna_related_files/processed/cat_count_table/tissue_cat={tissue_cat}_count_table_with_annotation.csv
cat_outliers:
  qual_filtered:
      junction_level: data/resources/absplice_rna_related_files/processed/cat_outliers/qual_filtered/tissue_cat={tissue_cat}_junction_level_signif.csv
      gene_level: data/resources/absplice_rna_related_files/processed/cat_outliers/qual_filtered/tissue_cat={tissue_cat}_gene_level.csv
  combine_gene_junction:
      gene_junction_signif: data/resources/absplice_rna_related_files/processed/cat_outliers/combine_gene_junction/gene_junction_signif/tissue_cat={tissue_cat}_signif.csv
      outlier_with_variant: data/resources/absplice_rna_related_files/processed/cat_outliers/combine_gene_junction/outlier_with_variant/{vcf_id}_tissue_cat={tissue_cat}_outlier_with_variant.csv
      minus_log10_pval: data/resources/absplice_rna_related_files/processed/cat_outliers/combine_gene_junction/minus_log10_pval/{vcf_id}_tissue_cat={tissue_cat}_FRASER_pval.csv